#!/bin/env python
 
import sys
import PSACCTReport

from PSACCTReport import FromCondor,UseArgs,gOutput,gBegin,GenericDaily,DailySiteVOReportFromDailyConf,DateToString,CheckDB
import sys

def main(argv=None):
    UseArgs(argv)

    if not CheckDB() :
        return 1

    print "OSG usage summary (midnight to midnight central time) for %s\nincluding all jobs that finished in that time period.\nWall Duration is expressed in hours and rounded to the nearest hour.\nDeltas are the differences with the previous day.\nIf the number of jobs stated for a site is always 1\nthen this number is actually the number of summary records sent.\n" % DateToString(PSACCTReport.gBegin,False)

    argOutput = PSACCTReport.gOutput
    #PSACCTReport.DailySiteReport(PSACCTReport.gBegin,output=argOutput);
    #print
    #PSACCTReport.DailyVOReport(PSACCTReport.gBegin,output=argOutput);
    print "From the results sent directly to the Summary database"
    print
    GenericDaily( DailySiteVOReportFromDailyConf(fromGratia = False, header = False), PSACCTReport.gBegin, output=argOutput);
    #print
    #print "From the results sent to the detailed Gratia database"
    #print
    #GenericDaily( DailySiteVOReportFromDailyConf(True), PSACCTReport.gBegin, output=argOutput);
    

if __name__ == "__main__":
    sys.exit(main())



