#!/bin/env python
 
import sys
import PSACCTReport

from PSACCTReport import FromCondor,UseArgs,gOutput,gBegin,CheckDB
import sys

def main(argv=None):
    UseArgs(argv)

    if not CheckDB() :
        return 1

    argOutput = PSACCTReport.gOutput
    PSACCTReport.DailySiteReport(PSACCTReport.gBegin,output=argOutput);
    print
    PSACCTReport.DailyVOReport(PSACCTReport.gBegin,output=argOutput, header = False);
    print
    PSACCTReport.DailySiteVOReport(PSACCTReport.gBegin,output=argOutput, header = False);
    print
    PSACCTReport.DailyVOSiteReport(PSACCTReport.gBegin,output=argOutput, header = False);

if __name__ == "__main__":
    sys.exit(main())



