#!/bin/bash

# Script to remove libs and other files in common dirs prior to
# updating.

rm -fv  gratia/*.hbm.xml \
        conf/logging.properties \
        conf/log4j-trustmanager.properties

rm -rfv common/classes/net/sf/gratia

exit $?
