#!/bin/bash
################################################################
# John Weigand (3/5/12)
#
# Gratia Collector Tomcat configuration.
################################################################
function logit {
  echo "$1"
}
#---------------
function logerr {
  logit "ERROR: $1";exit 1
}
#---------------
function verify_root {
  if [ "`id -u`" != "0" ];then
    logerr "You must be root to execute this."
  fi
}
#---------------
function runit {
  local cmd="$1"
  logit "... executing: $cmd"
  $cmd;rtn=$?
  if [ "$rtn" != "0" ];then
    logerr "process failed: $cmd"
  fi
}
#---------------
function find_tomcat_version {
  [ ! -z "$TOMCAT_VERSION" ] && return  # already have it
  if [ -r "/etc/tomcat5/tomcat5.conf" ];then
    export TOMCAT_VERSION=tomcat5    
  elif [ -r "/etc/tomcat6/tomcat6.conf" ];then
    export TOMCAT_VERSION=tomcat6    
  else
    logerr "Unable to determine tomcat version"
  fi
}
#---------------
function configuring_tomcat {
  logit "--- Configuring Tomcat and server.xml ---"
  script="/var/lib/trustmanager-tomcat/configure.sh"
  if [ ! -x "$script" ];then
    logerr "Configuration file does not exist or is not executable: $script"
  fi
  runit "/var/lib/trustmanager-tomcat/configure.sh"
  find_tomcat_version
  case "$TOMCAT_VERSION" in
      "tomcat5" )
        dest=/usr/share/java/log4j.jar
	link=/usr/share/tomcat5/common/lib/log4j.jar
        if [ ! -f $link ]
	then  
        	logit "--- adding log4j.jar to /usr/share/tomcat5/common/lib ---"
        	runit "ln -s $dest $link"
        	logit "`ls -l $link`"
	fi
        ;;
      "tomcat6" )
         ;;
        * ) logerr "This version of tomcat is not supported: $TOMCAT_VERSION" ;;
    esac
                                                                                                                            77,9          73%

  logit
}
#---------------
function update_tomcat_conf {
  find_tomcat_version 
  logit "--- Updating ${TOMCAT_VERSION}.conf ---"
  cfg=/usr/share/${TOMCAT_VERSION}/conf/${TOMCAT_VERSION}.conf
  if [ ! -f $cfg ];then
    logerr "tomcat config file does not exist: $cfg"
  fi
  runit "cp -p $cfg ${cfg}.${BACKUP_DATE}"
  cat >>$cfg <<EOF
JAVA_OPTS=' -server -Xmx1024M -XX:MaxPermSize=256m -Dcom.mchange.v2.c3p0.management.ManagementCoordinator=com.mchange.v2.c3p0.management.NullManagementCoordinator -Dcom.sun.management.jmxremote'
EOF
  logit
}
#----------------
function update_server_xml {
  find_tomcat_version 
  logit "--- Updating server.xml ---"
  server_xml=/usr/share/${TOMCAT_VERSION}/conf/server.xml
  logit "Replacing Tomcat server.xml file: $server_xml"
  runit "cp -p $server_xml ${server_xml}.${BACKUP_DATE}"
  runit "cp -p $SERVER_XML_TEMPLATE $server_xml"
  runit "chmod 644         $server_xml"
  runit "chown tomcat.root $server_xml"
  logit
}
#-------------------
function usage {
  echo "
Usage: $PGM 

Configures tomcat for a Gratia Collector RPM instance:
1. runs /var/lib/trustmanager-tomcat/configure.sh
2. appends to the tomcat5/6.conf a new JAVA_OPTS 
3. creates a new server.xml from a template 
"
}
#### MAIN ############################################################
PGM=`basename $0`
BACKUP_DATE=`date +'%Y%m%d-%H%M'`
SERVER_XML_TEMPLATE=/usr/share/gratia/server.xml.template

logit "====== Configuring Tomcat for gratia ===="
verify_root
configuring_tomcat
update_tomcat_conf
update_server_xml
logit "====== Completed Tomcat configuration for Gatia ==="
exit 0
