#!/bin/bash
########################################################################
# Note: This should be executed by root before tomcat is started.
#       The MySql instance needs to be running.
########################################################################
function usage {
echo "
Usage: ${PGM}

Performs the following on the MySql instance for a Gratia Service
  1. Verifies MySql is installed
  2. Verifies the mysqld daemon is running  
  3. Verifies that the port specified in the Gratia configuration file
     matches that set in the MySql /etc/my.cnf file.
     Note: this not comprehensive if they really have different ports
           for mysqld and the clients.
  4. Checks to see if an existing MySql instance has the root password
     set and verifies against the Gratia authorization properties file.
     If root password is not set and the Gratia Authorization specifies
     it, root passowrd will be set.
  5. Creates the mysql gratia database
  6. Sets privileges for Gratia users
"
########################################################################
}

#----------------------------------
function get_mysql_attributes {
  DBPORT=`grep ^service.mysql.url $CONFIGURATIONS | tr ':' ' ' | tr '/' ' ' | awk '{print $4;}'`
  DBNAME=`grep ^service.mysql.url $CONFIGURATIONS | tr ':' ' ' | tr '/' ' ' | awk '{print $NF;}'`
  DBHOST=`grep ^service.mysql.url $CONFIGURATIONS | tr ':' ' ' | tr '/' ' ' | awk '{print $3;}'`

  DBUSER=`grep           ^service.mysql.user         $AUTHORIZATIONS | tr '=' ' ' | awk '{print $NF;}'`
  DBPASSWD=`grep         ^service.mysql.password     $AUTHORIZATIONS | tr '=' ' ' | awk '{print $NF;}'`
  DBREADER=`grep         ^service.reporting.user     $AUTHORIZATIONS | tr '=' ' ' | awk '{print $NF;}'`
  DBREADERPASSWD=`grep   ^service.reporting.password $AUTHORIZATIONS | tr '=' ' ' | awk '{print $NF;}'`
  DBROOTPASSWD=`grep     ^service.mysql.rootpassword $AUTHORIZATIONS | tr '=' ' ' | awk '{print $NF;}'`

# HK this is new as of September 2014
  DBROOTUSER=`grep       ^service.mysql.rootuser     $AUTHORIZATIONS | tr '=' ' ' | awk '{print $NF;}'`
  echo $DBROOTUSER
}

#-------------------------------
#-------------------------------
function verify_mysql_installed {
  echo "... validating MySql is installed"
  if [ ! -e "$MYSQL_CONFIG" ];then
    echo "ERROR: Could not complete Gratia configuration"
    echo "Cannot find $MYSQL_CONFIG"
    echo "You must install and configure MySQL 5 before configuring Gratia."
    exit 1
  fi
  if [ ! -e "/etc/init.d/mysqld" ];then
    echo "ERROR: Could not find initd service: /etc/init.d/mysqld"
    echo "Did you install of MySql work correctly?"
    exit 1
  fi
}

#-------------------------------
function verify_mysql_running {
  echo "... verifying mysqld daemon is running"
  cmd="service mysqld status"
  echo "$cmd"
  $cmd;rtn=$?
  if [ "$rtn" != "0" ];then
    echo "ERROR: The MySql mysqld daemon does not appear to be running"
    echo "You will need it running to complete this installation."
    exit 1
  fi
}
#-------------------------------
function validate_mysql_config {
  verify_mysql_installed
  echo "... validating MySql port being used"
  mysql_cnf_port="`egrep -v '^#' $MYSQL_CONFIG | grep port | sed -e's/=/ /' | awk '{print $2}' | sort -u `"
  [ "x$mysql_cnf_port" = "x" ] && mysql_cnf_port=$DEFAULT_MYSQL_PORT
  if [ "$DBPORT" != "$mysql_cnf_port" ];then
    echo "ERROR: The MySql port specified in the Gratia configuration file does not"
    echo "match the port specified in the mysql configuration file."
    echo "  File: $CONFIGURATIONS"
    echo "  Attribute: `grep ^service.mysql.url $CONFIGURATIONS`"
    echo "  MySql: $MYSQL_CONFIG"
    echo "  Attribute: `egrep -v '^#' $MYSQL_CONFIG | grep port`"
    echo "Please correct."
    exit 1
  fi
  echo "... port: $DBPORT"
}



#-------------------------------
#-------------------------------
#-------------------------------
function check_if_root_passwd_set {
  # Attempts to determine if the root password has been set already
  echo "quit" | mysql -B --unbuffered  --user=root --port=$DBPORT &>/dev/null;rtn=$?
  if [ "$rtn" = "0" ];then
    ROOT_SET=0 
    echo "... root password has not been set yet."
  else
    ROOT_SET=1
    echo "... root password has already been set."
  fi
}
function verify_root_pswd {
  # If the root password is already set, then we are verifying the one
  # in the Gratia authorization file is correct.
  [ "$ROOT_SET" = "0" ] && return
  echo "... verifying if root password is correct"
  echo "quit" | mysql `mysql_arguments` &>/dev/null;rtn=$?
  rm -f $TMPPSWD
  if [ "$rtn" != "0" ];then 
    echo "The root mysql password has already been set and the one specified in the "
    echo "Gratia authorization file does not match:"
    echo "  File: $AUTHORIZATIONS"
    echo "  Attribute: service.mysql.rootpassword"
    echo "Please correct."
    exit 1 
  fi
}
#-------------------------------
#-------------------------------
#-------------------------------
#-------------------------------
function check_if_root_passwd_set_remote {
  ssh $MSHOST "echo \"quit\" | mysql -B --unbuffered --user=root &>/dev/null";rtn=$?
  if [ "$rtn" = "0" ];then
    ROOT_SET=0 
    echo "... root password has not been set yet."
  else
    ROOT_SET=1
    echo "... root password has already been set."
  fi
}
function verify_root_pswd_remote {
  [ "$ROOT_SET" = "0" ] && return
  echo "... verifying if root password is correct"

  ssh $MSHOST "echo \"quit\" | mysql -B --unbuffered --user=root --password=${DBROOTPASSWD} &>/dev/null";rtn=$?
#HK> for remote, mysql_arguments function is not working
#  echo "quit" | mysql `mysql_arguments` &>/dev/null;rtn=$?
#  rm -f $TMPPSWD
  if [ "$rtn" != "0" ];then 
    echo "The root mysql password has already been set and the one specified in the "
    echo "Gratia authorization file does not match:"
    echo "  File: $AUTHORIZATIONS"
    echo "  Attribute: service.mysql.rootpassword"
    echo "Please correct."
    exit 1
  fi
}




#-------------------------------
function mysql_arguments {
# HK> used in function verify_root_pswd() and  function update_mysql()
  # If the root password is already set, then a tmp file is needed
  # so as not to show the password in the mysql execution.
  local passwd_arg=""
  if [ "$ROOT_SET" = "1" ];then 
    passwd_arg=" --defaults-extra-file=$TMPPSWD "
    create_tmp_passwd_file
  fi
  echo "$passwd_arg -B --unbuffered  --user=root --port=$DBPORT" 
}
# HK> used only in function mysql_arguments() above
function create_tmp_passwd_file {
  cat >$TMPPSWD <<EOF
[client]
password="${DBROOTPASSWD}"
EOF
  chmod 600 $TMPPSWD
}
#-------------------------------






#-------------------------------
#-------------------------------
#-------------------------------
function create_gratia_sql_updates_file {
  > $TMPSQL
  #-- create the root password is needed --
  if [ "$ROOT_SET" = "0" ];then 
    echo "... creating the root password specified" 
    if [ "x$DBROOTPASSWD" = "x" ] || [ $DBROOTPASSWD = "service.mysql.rootpassword" ];then
      DBROOTPASSWD=""
    fi
    cat >$TMPSQL <<EOF
use mysql;
UPDATE user SET PASSWORD=PASSWORD("$DBROOTPASSWD") WHERE User = 'root';
FLUSH PRIVILEGES;
EOF
  fi
  #-- create database and set privileges --
  echo "... creating $DBNAME database and updating privileges"
  [ $DBHOST == "localhost" ] && host=`hostname -f` || host=$DBHOST
  cat >>$TMPSQL <<EOF
CREATE database $DBNAME;
GRANT ALL PRIVILEGES ON $DBNAME.* TO '$DBUSER'@'localhost'   IDENTIFIED BY '$DBPASSWD';
GRANT ALL PRIVILEGES ON $DBNAME.* TO '$DBUSER'@'$host'       IDENTIFIED BY '$DBPASSWD';
GRANT SELECT,EXECUTE ON $DBNAME.* TO '$DBREADER'@'localhost' IDENTIFIED BY '$DBREADERPASSWD';
GRANT SELECT,EXECUTE ON $DBNAME.* TO '$DBREADER'@'$host'     IDENTIFIED BY '$DBREADERPASSWD';
GRANT ALL PRIVILEGES ON $DBNAME.* TO 'root'@'localhost'      IDENTIFIED BY '$DBROOTPASSWD';
GRANT ALL PRIVILEGES ON $DBNAME.* TO 'root'@'$DBHOST'        IDENTIFIED BY '$DBROOTPASSWD';
EOF
  chmod 600 $TMPSQL
}
#----------------------------
function update_mysql {
  cat $TMPSQL | mysql `mysql_arguments`;rtn=$?
  rm -f $TMPSQL $TMPPSWD
  if [ "$rtn" != "0" ];then
    echo "ERROR: The attempt to create/update the Gratia database failed."
    exit 1
  fi
}


#----------------------------
#----------------------------
#----------------------------
#----------------------------
function update_mysql_remote {

  if [ "$ROOT_SET" = "0" ];then 
    echo "... creating the root password specified" 
    if [ "x$DBROOTPASSWD" = "x" ] || [ $DBROOTPASSWD = "service.mysql.rootpassword" ];then
      DBROOTPASSWD=""
    fi
  fi
#HK> Normally DBROOTPASSWD is set by get_mysql_attributes
#HK> The function check_if_root_passwd_set()  and function verify_root_pswd() directly tries to use mysql as root without password to see if the root password is set or not
# If rootpasswd is not set, set it to null
# If rootpasswd is yes set, just make sure that it is same as DBROOTPASSWD
#HK> if the root password is NOT set, i.e. if it is set to service.mysql.rootpassword, then we manually set     DBROOTPASSWD=""
#HK> because
# if  service.mysql.rootpassword=
# then          grep     ^service.mysql.rootpassword service-authorization.properties | tr '=' ' ' | awk '{print $NF;}'
# returns       service.mysql.rootpassword
# i.e. DBROOTPASSWD=service.mysql.rootpassword
# if service.mysql.rootpassword=password
# then          grep     ^service.mysql.rootpassword service-authorization.properties | tr '=' ' ' | awk '{print $NF;}'
# returns       messi
# i.e. DBROOTPASSWD=password
##HK> Important thing is, we assume       DBROOTPASSWD for both root@MSHOST and root@GSHOST

    echo "... creating $DBNAME database and updating privileges"

# HK> We used to aggressively conduct the following 3 commands, but as of September 2014, we simply trust MySQL DBA to have done these commands for us.
#    ssh $MSHOST "mysql -uroot --password=${DBROOTPASSWD} --execute  'GRANT ALL PRIVILEGES ON        *.* TO \"root\"@\"$GSHOST\"    IDENTIFIED BY \"$DBROOTPASSWD\"'    mysql"
#    ssh $MSHOST "mysql -uroot --password=${DBROOTPASSWD} --execute  'GRANT ALL PRIVILEGES ON \$DBNAME.* TO \"root\"@\"$GSHOST\"    IDENTIFIED BY \"$DBROOTPASSWD\"'    mysql"
#    mysql -h $MSHOST -uroot --password=${DBROOTPASSWD}  --execute  "update user set Grant_priv=\"Y\" where Host=\"$GSHOST\" and User=\"root\"         " mysql

    mysql -h $MSHOST -u${DBROOTUSER} --password=${DBROOTPASSWD}  --execute  "CREATE database $DBNAME CHARACTER SET latin1 COLLATE latin1_swedish_ci"
    mysql -h $MSHOST -u${DBROOTUSER}  --password=${DBROOTPASSWD}  --execute  "GRANT ALL PRIVILEGES ON $DBNAME.* TO   \"$DBUSER\"@\"$GSHOST\"  IDENTIFIED BY \"$DBPASSWD\""       mysql
    mysql -h $MSHOST -u${DBROOTUSER}  --password=${DBROOTPASSWD}  --execute  "GRANT ALL PRIVILEGES ON $DBNAME.* TO   \"root\"@\"$GSHOST\"  IDENTIFIED BY \"$DBROOTPASSWD\""       mysql
    mysql -h $MSHOST -u${DBROOTUSER}  --password=${DBROOTPASSWD}  --execute  "GRANT SELECT,EXECUTE ON $DBNAME.* TO \"$DBREADER\"@\"$GSHOST\"  IDENTIFIED BY \"$DBREADERPASSWD\"" mysql
}

# The final strategy is as follows
# If GS and MS are different, we have to ask DBA of MySQL node to do the following
#mysql> use mysql;
#mysql> grant all privileges on      *.* to "root"@"gratianode.fnal.gov" identified by "password";
#mysql> update user set Grant_priv="Y"  where Host="gratianode.fnal.gov" and User="root";
#mysql> grant all privileges on gratia.* to "root"@"gratianode.fnal.gov" identified by "password";
# and the DBA should let GS admin know if "root" and "password" are different strings

# GS node admin should assign those strings from MS DBA to DBROOTUSER and DBROOTPASSWOD as defined in service-authorization.properties
# install-database script will simply use DBROOTUSER and DBROOTPASSWOD as defined in service-authorization.properties
# and will assume that DBROOTUSER in MySQL node has Grant_priv=Y
# and execute the following commands

# mysql -h $MS -u${DBROOTUSER} --password=${DBROOTPASSWD} --execute  "CREATE database $DBNAME CHARACTER SET latin1 COLLATE latin1_swedish_ci"
# mysql -h $MS -u${DBROOTUSER} --password=${DBROOTPASSWD} --execute  "GRANT ALL PRIVILEGES ON $DBNAME.* TO    \"$DBUSER\"@\"$GSHOST\"  IDENTIFIED BY \"$DBPASSWD\""       mysql
# mysql -h $MS -u${DBROOTUSER} --password=${DBROOTPASSWD} --execute  "GRANT SELECT,EXECUTE ON $DBNAME.* TO  \"$DBREADER\"@\"$GSHOST\"  IDENTIFIED BY \"$DBREADERPASSWD\"" mysql
# mysql -h $MS -u${DBROOTUSER} --password=${DBROOTPASSWD} --execute  "GRANT ALL PRIVILEGES ON $DBNAME.* TO \"DBROOTUSER\"@\"$GSHOST\"  IDENTIFIED BY \"$DBROOTPASSWD\""   mysql

# And make sure post-install is also using DBROOTUSER, not root







### MAIN ######################################################
#set -x
PGM=`basename $0`
CONFIGURATIONS=/etc/gratia/services/service-configuration.properties
AUTHORIZATIONS=/etc/gratia/services/service-authorization.properties
TMPPSWD=/tmp/.${PGM}.pwsd.$$   # very temporary passwd file
TMPSQL=/tmp/.${PGM}.sql.$$     # very temporary sql file
MYSQL_CONFIG=/etc/my.cnf
DEFAULT_MYSQL_PORT=3306

case $1 in
 "?" | "-?" | "-h" | "-help" | "--help" ) usage;exit 1;;
  * ) ;;
esac

echo "
Creating Gratia database based on the properties you updated in these files:
  $CONFIGURATIONS
  $AUTHORIZATIONS"



get_mysql_attributes

GSHOST=`hostname -f`
[ $DBHOST == "localhost" ] && MSHOST=`hostname -f` || MSHOST=$DBHOST
echo "GS = $GSHOST"
echo "MS = $MSHOST"


if [ $GSHOST = $MSHOST ] 
then
echo "GS and MS running in one node"
verify_mysql_installed 
verify_mysql_running 
validate_mysql_config

check_if_root_passwd_set  # ROOT_SET=1 - password set / ROOT_SET=0 - pswd not set
verify_root_pswd 
create_gratia_sql_updates_file 
update_mysql 

else

echo "GS and MS running in two nodes"
##HK> Important thing is, for remote case, we do not have remote versions of
# verify_mysql_installed, verify_mysql_running , validate_mysql_config
# i.e. we assume that MS is installed and running with correct configuration
# we just proceed to the root password and privilege
#check_if_root_passwd_set_remote
#verify_root_pswd_remote

update_mysql_remote
fi

echo "
Gratia database installation complete.
"

exit 

