#!/bin/env python
 
import sys
import AccountingReports

from AccountingReports import FromCondor,UseArgs,gOutput,gBegin,CheckDB,gGroupBy
import sys

def main(argv=None):
    UseArgs(argv)
 
    if not CheckDB() :
        return 1

    argOutput = AccountingReports.gOutput

    if (argOutput == "all"):
       text = {}
       for iterOutput in ("text","csv","html"):
          text[iterOutput] = AccountingReports.GenericDailyStatus( AccountingReports.DailySiteJobStatusConf(header=True,groupby=AccountingReports.gGroupBy),AccountingReports.gBegin,output=iterOutput )
       AccountingReports.sendAll(text)

    else:
       print AccountingReports.GenericDailyStatus( AccountingReports.DailySiteJobStatusConf(header=True,groupby=AccountingReports.gGroupBy),AccountingReports.gBegin,output=argOutput )

if __name__ == "__main__":
    sys.exit(main())



