#!/bin/env python
 
import sys
import AccountingReports

from AccountingReports import FromCondor,UseArgs,gOutput,gBegin,CheckDB,gGroupBy
import sys

def main(argv=None):
    UseArgs(argv)
 
    if not CheckDB() :
        return 1

    argOutput = AccountingReports.gOutput
    AccountingReports.GenericDailyStatus( AccountingReports.DailySiteJobStatusConf(header=True,groupby=AccountingReports.gGroupBy),AccountingReports.gBegin,output=argOutput )
    print
    #AccountingReports.GenericDailyStatus( AccountingReports.DailySiteJobStatusConf(header=True,CondorSpecial=False),AccountingReports.gBegin,output=argOutput )
    #print

if __name__ == "__main__":
    sys.exit(main())



