#!/bin/env python
 
import sys
import AccountingReports

from AccountingReports import FromCondor,UseArgs,gOutput,gBegin,CheckDB,gGroupBy
import sys

def main(argv=None):
    UseArgs(argv)
 
    if not CheckDB() :
        return 1

    print "Summary of the job exit status (midnight to midnight central time) for %s\nincluding all jobs that finished in that time period.\n\nFor Condor the value used is taken from 'ExitCode' and NOT from 'Exit Status'"
    print "\nFor VO: ", AccountingReports.gVOName, "\n"
    
    argOutput = AccountingReports.gOutput
    AccountingReports.GenericDailyStatus( AccountingReports.DailySiteJobStatusConf(header=False,groupby="ForVO",VOName=AccountingReports.gVOName),AccountingReports.gBegin,output=argOutput )
    print

    AccountingReports.RangeUserReport(range_begin = AccountingReports.gBegin,
                             range_end = AccountingReports.gEnd ,
                             output=argOutput,
                             selectVOName=AccountingReports.gVOName);

if __name__ == "__main__":
    sys.exit(main())



