#!/bin/env python
 
import sys
import AccountingReports

from AccountingReports import FromCondor,UseArgs,gOutput,gBegin,CheckDB
import sys

def main(argv=None):
    UseArgs(argv)

    if not CheckDB() :
        return 1

    argOutput = AccountingReports.gOutput
    AccountingReports.RangeSummup(range_begin = AccountingReports.gBegin,range_end = AccountingReports.gEnd ,output=argOutput);
    print
    AccountingReports.DailySiteReport(AccountingReports.gBegin,output=argOutput);
    print
    AccountingReports.DailyVOReport(AccountingReports.gBegin,output=argOutput, header = False);
    print
    AccountingReports.DailySiteVOReport(AccountingReports.gBegin,output=argOutput, header = False);
    print
    AccountingReports.DailyVOSiteReport(AccountingReports.gBegin,output=argOutput, header = False);

if __name__ == "__main__":
    sys.exit(main())



