#!/bin/bash

TMP=`mktemp -d "${TMPDIR:-/tmp}/failure-summary.XXXXXXXXXX"`
[[ -d "$TMP" ]] || exit2

trap "rm -rf \"$TMP\" 2>/dev/null" EXIT

today=`date -u +'%Y/%m/%d 00:00:00 UTC'`
yesterday=`date -u +'%Y/%m/%d 00:00:00 UTC' -d 'yesterday'`
cat > "$TMP/mail.dat" <<EOF
Failure summary by VO and date for jobs completed yesteday
(between $yesterday and $today).

For Condor the value used is taken from 'ExitCode' and NOT from 'Exit Status'

EOF

cat > "$TMP/failure.sql" <<EOF
(select LCASE(J.VOName) as LVOName,
  T.SiteName as LSiteName,
  sum(Njobs) as 'FailedJobs',
  X.TotalJobs,
  FORMAT(100.0 * sum(NJobs) / X.TotalJobs, 1) as pcFailed
 from JobUsageRecord J, Site T, Probe P,
  (select LCASE(XJ.VOName) as XVOName,
     XT.SiteName as XSiteName,
     sum(Njobs) as 'TotalJobs'
   from JobUsageRecord XJ, Site XT, Probe XP
   where
     EndTime >= CURDATE() - INTERVAL 1 DAY and
     EndTime < CURDATE() and
     XP.probename = XJ.ProbeName and
     XT.siteid = XP.siteid
   group by XVOName, XSiteName) X
 where
   EndTime >= CURDATE() - INTERVAL 1 DAY and
   EndTime < CURDATE() and
	 J.StatusDescription != "Condor Exit Status" and
   J.Status != 0 and
   P.probename = J.ProbeName and
   T.siteid = P.siteid and
   T.SiteName = XSiteName and
   LCASE(J.VOName) = XVOName
 group by LVOName, LSiteName)
UNION ALL
(select LCASE(J.VOName) as LVOName,
  T.SiteName as LSiteName,
  sum(Njobs) as 'FailedJobs',
  X.TotalJobs,
  FORMAT(100.0 * sum(NJobs) / X.TotalJobs, 1) as '% Failed'
 from JobUsageRecord J, Site T, Probe P,
  (select LCASE(XJ.VOName) as XVOName,
     XT.SiteName as XSiteName,
     sum(Njobs) as 'TotalJobs'
   from JobUsageRecord XJ, Site XT, Probe XP
   where
     EndTime >= CURDATE() - INTERVAL 1 DAY and
     EndTime < CURDATE() and
     XP.probename = XJ.ProbeName and
     XT.siteid = XP.siteid and
     LCASE(VOName) like 'engage%'
   group by XVOName, XSiteName) X, Resource R
 where
   EndTime >= CURDATE() - INTERVAL 1 DAY and
   EndTime < CURDATE() and
   P.probename = J.ProbeName and
   T.siteid = P.siteid and
   T.SiteName = XSiteName and
   LCASE(J.VOName) = XVOName and
   R.dbid = J.dbid and
   R.description = 'ExitCode' and
   R.Value != 0
 group by LVOName, LSiteName)
order by LVOName, ABS(pcFailed) desc;
EOF

mysql -u reader -h gratia-db01.fnal.gov -P 3320 --password="reader" -B -t gratia \
> "$TMP/failure.txt" < "$TMP/failure.sql"

cat > "$TMP/failure.pl" <<\EOF
#!/usr/bin/perl -w
use strict;

while (<>) {
	chomp;
	next if m&^\+[-\+]*\+$&;
	my @fields = split /\s*\|\s*/;
	@fields = map { if (m&^[\d\.]+$&) {$_;} else { s&\"&\"\"&g; "\"$_\"" } } @fields; 
	shift @fields;
	print join(",", @fields), "\n";
}
EOF

chmod +x "$TMP/failure.pl"

"$TMP/failure.pl" "$TMP/failure.txt" > "$TMP/failure.csv"

cat "$TMP/mail.dat" "$TMP/failure.txt" | \
EMAIL="Gratia Operation <gratia-operation@opensciencegrid.org>" mutt \
-a "$TMP/failure.csv" -s "Job Failure Summary $yesterday - $today" \
osg-accounting-info@fnal.gov
