#!/bin/env python
 
import sys
import AccountingReports

from AccountingReports import FromCondor,UseArgs,gOutput,gBegin,CheckDB
import sys

def main(argv=None):
    UseArgs(argv)

    if not CheckDB() :
        return 1

    argOutput = AccountingReports.gOutput

    if (argOutput == "all"):
       text = {}
       for iterOutput in ("text","csv","html"):
          text[iterOutput] = AccountingReports.LongJobs(range_begin = AccountingReports.gBegin,
                             range_end = AccountingReports.gEnd ,
                             output=iterOutput);
       AccountingReports.sendAll(text)
    else:
          print AccountingReports.LongJobs(range_begin = AccountingReports.gBegin,
                             range_end = AccountingReports.gEnd ,
                             output=iterOutput);

if __name__ == "__main__":
    sys.exit(main())

