#!/bin/env python
 
import sys
import PSACCTReport

from PSACCTReport import FromCondor,UseArgs,gOutput,gBegin,CheckDB
import sys

def main(argv=None):
    UseArgs(argv)

    if not CheckDB() :
        return 1

    argOutput = PSACCTReport.gOutput

    PSACCTReport.RangeSummup(range_begin = PSACCTReport.gBegin,
                             range_end = PSACCTReport.gEnd ,
                             output=argOutput);
    print

    
    PSACCTReport.RangeSiteReport(range_begin = PSACCTReport.gBegin,
                                 range_end = PSACCTReport.gEnd,
                                 output = argOutput,
                                 header = True,
                                 with_panda = PSACCTReport.gWithPanda);
    print
    PSACCTReport.RangeVOReport(range_begin = PSACCTReport.gBegin,
                               range_end = PSACCTReport.gEnd,
                               output = argOutput,
                               header = False,
                               with_panda = PSACCTReport.gWithPanda);
    print
    PSACCTReport.RangeSiteVOReport(range_begin = PSACCTReport.gBegin,
                                   range_end = PSACCTReport.gEnd,
                                   output = argOutput,
                                   header = False,
                                   with_panda = PSACCTReport.gWithPanda);
    print
    PSACCTReport.RangeVOSiteReport(range_begin = PSACCTReport.gBegin,
                                   range_end = PSACCTReport.gEnd,
                                   output = argOutput,
                                   header = False,
                                   with_panda = PSACCTReport.gWithPanda);

if __name__ == "__main__":
    sys.exit(main())



