#!/bin/env python
 
import sys
import AccountingReports

from AccountingReports import FromCondor,UseArgs,gOutput,gBegin,CheckDB
import sys

def main(argv=None):
    UseArgs(argv)

    if not CheckDB() :
        return 1

    argOutput = AccountingReports.gOutput

    AccountingReports.RangeSummup(range_begin = AccountingReports.gBegin,
                             range_end = AccountingReports.gEnd ,
                             output=argOutput);
    print

    
    AccountingReports.RangeSiteReport(range_begin = AccountingReports.gBegin,
                                 range_end = AccountingReports.gEnd,
                                 output = argOutput,
                                 header = True,
                                 with_panda = AccountingReports.gWithPanda);
    print
    AccountingReports.RangeVOReport(range_begin = AccountingReports.gBegin,
                               range_end = AccountingReports.gEnd,
                               output = argOutput,
                               header = False,
                               with_panda = AccountingReports.gWithPanda);
    print
    AccountingReports.RangeSiteVOReport(range_begin = AccountingReports.gBegin,
                                   range_end = AccountingReports.gEnd,
                                   output = argOutput,
                                   header = False,
                                   with_panda = AccountingReports.gWithPanda);
    print
    AccountingReports.RangeVOSiteReport(range_begin = AccountingReports.gBegin,
                                   range_end = AccountingReports.gEnd,
                                   output = argOutput,
                                   header = False,
                                   with_panda = AccountingReports.gWithPanda);

if __name__ == "__main__":
    sys.exit(main())



