#!/bin/env python
 
import AccountingReports,datetime,sys

def main(argv=None):
    AccountingReports.UseArgs(argv)

    if not AccountingReports.CheckDB() :
        return 1

    argOutput = AccountingReports.gOutput

    AccountingReports.NonReportingSites(when = AccountingReports.gBegin, output=argOutput) # datetime.date(2008,02,01))

    #AccountingReports.RangeSummup(range_begin = AccountingReports.gBegin,
    #                         range_end = AccountingReports.gEnd)

if __name__ == "__main__":
    sys.exit(main())
