#!/bin/env python
 
import sys
import AccountingReports

from AccountingReports import UseArgs,gOutput,gBegin,CheckDB,gConfig
import sys

def main(argv=None):
    UseArgs(argv)

    if not CheckDB() :
        return 1

    argOutput = AccountingReports.gOutput

    if (argOutput == "all"):
       text = {}
       for iterOutput in ("text","csv","html"):
          text[iterOutput] = ( AccountingReports.SoftwareVersion(range_begin = AccountingReports.gBegin, range_end = AccountingReports.gEnd ,output=iterOutput) )

       AccountingReports.sendAll(text)

    else:
       print AccountingReports.SoftwareVersion(range_begin = AccountingReports.gBegin,range_end = AccountingReports.gEnd ,output=argOutput)


if __name__ == "__main__":
    sys.exit(main())



