#!/bin/env python
 
import sys
import PSACCTReport

from PSACCTReport import UseArgs,gOutput,gBegin,CheckDB,gConfig
import sys

def main(argv=None):
    UseArgs(argv)

    if not CheckDB() :
        return 1

    argOutput = PSACCTReport.gOutput

    if (argOutput == "all"):
       text = {}
       for iterOutput in ("text","csv","html"):
          text[iterOutput] = ( PSACCTReport.SoftwareVersion(range_begin = PSACCTReport.gBegin, range_end = PSACCTReport.gEnd ,output=iterOutput) )

       PSACCTReport.sendAll(text)

    else:
       PSACCTReport.SoftwareVersion(range_begin = PSACCTReport.gBegin,range_end = PSACCTReport.gEnd ,output=argOutput)


if __name__ == "__main__":
    sys.exit(main())



