call setup.bat
call cleanup.bat
call build-services.bat
call build-soap.bat
call build-servlets.bat
call build-security.bat
call build-reporting.bat
call build-reports.bat
call build-configurator.bat
call build-administration.bat
call build-tarballs.bat
