#!/bin/bash
########################################################################
# install-nightly-builds
#
# Quick script to install all the nightly build collectors.
#
# Note that the host credential for the machine upon which this script
# runs must be listed in root's .k5login for each of the collector
# machines.
#
# For the situation at the time of writing, this means:
#  host/gr6x3.fnal.gov@FNAL.GOV
# is in root's .k5login on gr8x{2,3,4}.
#
# 2010/03/24 Chris Green
########################################################################
TMP=`mktemp ${TMPDIR:-/tmp}/install-nightly-builds.XXXXXXXXXX`
trap "rm \"$TMP\" 2>/dev/null" EXIT

if (( $(id -u) == 0 )); then
  # If we're running this script as root, get the host credentials.
  export KRB5CCNAME=$TMP
  kinit -k
fi

VERSION_OPT="-B"
VERSION_ARG=latest
SCRIPT_TOPDIR=~gratia/gratia-builds/gratia-${VERSION_ARG}
INSTALL_SCRIPT=${SCRIPT_TOPDIR}/build-scripts/install-release
CONFIG_DIR=${SCRIPT_TOPDIR}/common/configuration
MAILTO=gratia-builds@fnal.gov
for INSTANCE in nightly_{batch,psacct,osg_daily}; do
  service=nbuild
  ${INSTALL_SCRIPT} -t -p -a \
                  $VERSION_OPT $VERSION_ARG \
                  -C ${CONFIG_DIR}/collector-${service}.dat \
                  -c $INSTANCE -m $MAILTO
done
