#!/bin/bash
########################################################################
# install-nightly-builds
#
# Quick script to install all the nightly build collectors.
#
# Note that the host credential for the machine upon which this script
# runs must be listed in root's .k5login for each of the collector
# machines.
#
# For the situation at the time of writing, this means:
#  host/gr6x3.fnal.gov@FNAL.GOV
# is in root's .k5login on gr8x{2,3,4}.
#
# 2010/03/24 Chris Green
########################################################################
prog=${0##*/}

####################################
# Required function do_installs
function do_installs() {
  for c in nightly_{batch,psacct,osg_daily}; do
    printf "########################################################################\n"
    "${INSTALL_SCRIPT}" -t -p -a \
                        "$VERSION_OPT" "$VERSION_ARG" \
                         -C "${CONFIG_DIR}/collector-nightly.dat" \
                         -m "$MAILTO" \
                         -c "${c}"
  done
}
####################################

# Install-related variables.
VERSION_OPT="-B"
VERSION_ARG=latest
SCRIPT_TOPDIR=~gratia/gratia-builds/gratia-${VERSION_ARG}
INSTALL_SCRIPT=${SCRIPT_TOPDIR}/build-scripts/install-release
CONFIG_DIR=${SCRIPT_TOPDIR}/common/configuration
MAILTO=gratia-builds@fnal.gov

# Handle build retries.
(( max_retries = 5 ))
(( retry = 0 ))

if [[ ! -r "${SCRIPT_TOPDIR}" ]]; then
  echo "ERROR: specified script top directory \"${SCRIPT_TOPDIR}\"" 1>&2
  exit 1
fi

# Make sure the build is actually ready to be used.
while [[ ! -r "${SCRIPT_TOPDIR}/target/gratia.tar" ]] && (( retry < max_retries )); do
  printf "WARNING: build not complete -- waiting 1 minute (retry %d of %d)\n"  \
    $(( ++retry )) $(( max_retries ))
  sleep 60
done

# Failure.
if (( retry > max_retries )); then # failed
  echo "ERROR: build was not completed in time to install: please check" 1>&2
  exit 1
fi

########################################################################
# Main program.
####################################

. ~gratia/gratia-builds/gratia-latest/install-group "$@"
