#!/bin/bash
########################################################################
# install-release
#
# Low-fuss wrapper around gratia-upgrade.sh, which is a wrapper around
# upgrade-gratia-local.sh, which is a wrapper around
# configure-collector. Sheesh.
########################################################################

####################################
# Useful variables
username=${USER:-${LOGNAME:-$(whoami)}}

####################################

########################################################################
# Functions

####################################
# usage
function usage() {
cat 1>&2 <<EOF
${0##*/} [<opt>] -R <release>
${0##*/} [<opt>] -B <official-build>
${0##*/} [<opt>] -L <full-release-path>
${0##*/} [<opt>] <release> (deprecated)
${0##*/} [-h]

Build-specifying options:
   -R <release>
      Official release (found as ~gratia/gratia-releases/gratia-<release>).
   -B <official-build>
      Official build (found as ~gratia/gratia-builds/gratia-<official-build>).
   -L <full-release-path>
      Local build (found as <full-release-path>).

Help:
   -h
      This help.

Options:
   -a
      Auto-start collector (default no start).

   -C <config-dat>
      Specify explicitly the config file from which to take the instance
      configuration.
      
   -c <config>
      Instance name is tomcat-<config> (except see -p).

   -t
      Install latest tomcat from ~gratia/tomcat-tarballs.

   -m <notify-mail>[,...]
      Comma-separated list of email addresses for notification of release.

   -p
      Production: shorthand for "-m gratia-operation@fnal.gov." Also
      triggers an extra check for a specified configuration name.

   -v
      Verbose: mention a little more about what we're doing.

Default config name is current user name ($username), unless -p is
specified (in which case there is no default and -c is required).

Examples

   Install and start a development collector tomcat-greenc as root on
   the machine in question:

      install-release -a -c greenc -L ~greenc/gratia-test

   Install and start a development collector tomcat-greenc remotely
   (assuming user is greenc):

      install-release -a -L ~greenc/gratia-test

   Install an integration collector with the latest build (manual
   start):

      install-release -c itb_gratia_itb -B latest

NOTES

   Any specified instance (either explicitly with -c or implicitly as
   <user>) must correspond to a configuration cluse in a collector-*.dat
   file. See gratia/common/configuration/collector*.dat for examples.

EOF
}
####################################

####################################
# get_config
#
# Get config or property item
function get_config() {
  OPTIND=1  
  while getopts :pv OPT; do
    case $OPT in
      v)
         local verbose=1
         ;;
      p)
         local config_opt=obtain-properties-item
         ;;
      *)
         return 1;
    esac
  done
  shift $[ OPTIND - 1 ]
  local item=$1
  if (( ${verbose:-0} )); then
    echo "Executing ${get_config_cmd[@]} --${config_opt:-obtain-config-item} $item $config_name"
  fi
  "${get_config_cmd[@]}" --${config_opt:-obtain-config-item} $item $config_name \
   2>/dev/null | sed -ne 's/\(config\|property\): '"$item"' = //p'
}
####################################

########################################################################
# Main body.

####################################
# Options
OPTIND=1

while getopts :B:C:L:R:ac:hm:ptv OPT; do
    case $OPT in
        B)
            type=build
            relarg=$OPTARG
            ;;
        C)
            config_dat=$OPTARG
            ;;
        L)
            type=local
            relarg=$OPTARG
            ;;
        R)
            type=release
            relarg=$OPTARG
            ;;
        a)
            autostart=1
            ;;        
        c)
            config_name=$OPTARG
            ;;
        h)
            usage
            exit 1
            ;;
        m)
            mail=$OPTARG
            ;;
        p)
            production=1
            ;;
        t)
            tomcat_arg=--install-tomcat
            ;;
        v)
            verbose=1
            ;;
        *)
            usage
            exit 2
    esac
done
shift $[ OPTIND - 1 ]

if [[ -z "type" ]]; then
  if [[ -n "$1" ]]; then
    echo "INFO: not specified -R, -L or -B options. Defaulting to official release $1" 1>&2
    type=release
    relarg="$1"
  else
    echo "ERROR: required options -R, -L or -B not specified." 1>&2
    usage
    exit 1
  fi
fi

####################################
# Setup
if [[ "$type" == "local" ]]; then
  release_dir="$relarg"
else
  tnstub="${type}s"
  release="$relarg"
  release_dir="/home/gratia/gratia-$tnstub/gratia-${release}"
fi

if [[ "$username" == "root" ]]; then
  echo "INFO: running as root. You should specify config-name. Mail will be sent to grid-accounting or gratia-operation as appropriate." 1>&2
else
  echo "INFO: running as $username. Collector host will be obtained from config for login and install as root." 1>&2 
  [[ -z "$mail" ]] && mail="${username}@fnal.gov"
fi

# Check for release integrity:
if ! { [[ -d "$release_dir" ]] && [[ -r "$release_dir" ]]; };  then
  echo "Specified release directory $release_dir does not exist or is not readable" 1>&2
  exit 2
fi

upgrade_script=${release_dir}/build-scripts/gratia-upgrade.sh
configure_script=${release_dir}/common/configuration/configure-collector

# configure command
  declare -a get_config_cmd=("$configure_script")
if [[ -n "$config_dat" ]]; then
  declare -a get_config_cmd=("${get_config_cmd[@]}" \
"-c" "$config_dat"
)
  declare -a config_dat_args=("--config" "$config_dat")
fi

# First, check for configuration (especially DB location).
install_prefix=`get_config install_prefix`
if (( ${production:-0} )); then
  if [[ -z "$config_name" ]]; then
    echo "Configuration name required for production installs" 1>&2
    usage
    exit 1
  fi
  [[ -z "$mail" ]] && mail="grid-accounting@fnal.gov"
else
  [[ -n "$config_name" ]] || config_name=$username
  [[ -z "$mail" ]] && mail="gratia-operation@fnal.gov"
fi
instance_name=$(get_config instance_name)
instance_name="tomcat-${instance_name:-$config_name}"
remote_host=`get_config remote_host`
db_host=`get_config db_host`
if [[ "$db_host" == "localhost" ]]; then
  db_host=$remote_host
fi

pswd_file=~gratia/.mysql-${db_host%%.*}

if [[ -z "$install_prefix" ]]; then
  echo "WARNING: configuration for instance $config_name does not specify install prefix: defaulting to /data" 1>&2
fi

if [[ ! -f "$pswd_file" ]]; then
  echo "ERROR: DB password file $pswd_file does not exist!" 1>&2
  exit 2
fi

if (( ${autostart:-0} )); then
  mail_opt=daily
else
  mail_opt=mail
fi

declare -a install_command=("$upgrade_script" --instance $instance_name \
                            "${config_dat_args[@]}" \
                            --config-name $config_name \
                            --source "$release_dir" \
                            --pswd xx --mysql "$pswd_file" \
                            --$mail_opt "$mail" \
                            ${tomcat_arg} \
                            --force-log4j)

# Now do different things if we're root
if [[ "$username" == "root" ]]; then
  printf "INFO: performing install of collector $instance_name ($config_name) locally with $type ${release:-build} from $release_dir ... "
  if (( ${autostart:-0} )); then
    "${install_command[@]}" >/dev/null 2>&1
    status=$?
  else
    yes n | "${install_command[@]}" >/dev/null 2>&1
    status=$?
  fi
else
  echo "INFO: checking root login privilege to install host $remote_host for user $username" 1>&2
  ssh root@$remote_host echo >/dev/null 2>&1
  status=$?
  if (( ${status:-1} != 0 )); then
    echo "ERROR: User $username unable to login as root to $remote_host for install!" 1>&2
    exit 2
  fi
  printf "INFO: performing install of collector $instance_name ($config_name) on host $remote_host with $type ${release:-build} from $release_dir ... " 1>&2
  if (( ${autostart:-0} )); then
    ssh root@$remote_host "${install_command[@]}" >/dev/null 2>&1
    status=$?
  else
    ssh root@$remote_host "yes n | ${install_command[@]}" >/dev/null 2>&1
    status=$?
  fi
fi

if (( ${status:-1} == 0 )); then
  echo "OK"
  if [[ "$username" == "root" ]]; then
    if (( ${autostart:-0} )); then
      echo "INFO: locally installed collector $instance_name ($config_name) is now running." 1>&2
    else
      echo "INFO: locally installed collector must be started -- use:" 1>&2
      echo "      service $instance_name start" 1>&2
    fi
  else
    if (( ${autostart:-0} )); then
      echo "INFO: collector $instance_name ($config_name) is now running on $remote_host" 1>&2
    else
      echo "INFO: collector $instance_name ($config_name) on $remote_host must be started -- use:" 1>&2
      echo "      ssh root@$remote_host service $instance_name start" 1>&2
    fi
  fi
else
  echo "FAILED!"
fi

echo "INFO: upgrade log may be found in $remote_host:$install_prefix/$instance_name-upgrade.log/"

exit $status


